### ISSUE TITLE
[Bug]: [teams] Kubernetes provider panic when adding application teams without specifying quota

### ISSUE THREAD

**Issue by aleixrm-scopely** [aws-ia/terraform-aws-eks-blueprints#819]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

v4.6.1

### What is your environment, configuration and the example used?

Terraform version: v1.2.6
Terragrunt version: v0.38.6
Kubernetes provider version: v2.12.1

Input:
```
application_teams = {
    namespace_1 = {
      users = [
        local.account_vars.locals.game_team_developer_role_arn
      ]
    }
  }
```

### What did you do and What did you see instead?

We tried to create a namespace for the given team without specifying labels or quotas, as fixed in https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/678, but the kubernetes provider looks that is still failing:

```
╷
│ Error: Plugin did not respond
│
│   with module.eks_blueprints.module.aws_eks_teams[0].kubernetes_resource_quota.this["satellites"],
│   on .terraform/modules/eks_blueprints/modules/aws-eks-teams/main.tf line 15, in resource "kubernetes_resource_quota" "this":
│   15: resource "kubernetes_resource_quota" "this" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks_blueprints.module.aws_eks_teams[0].kubernetes_role.team["satellites"],
│   on .terraform/modules/eks_blueprints/modules/aws-eks-teams/main.tf line 83, in resource "kubernetes_role" "team":
│   83: resource "kubernetes_role" "team" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks_blueprints.module.aws_eks_teams[0].kubernetes_role_binding.team["satellites"],
│   on .terraform/modules/eks_blueprints/modules/aws-eks-teams/main.tf line 101, in resource "kubernetes_role_binding" "team":
│  101: resource "kubernetes_role_binding" "team" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks_blueprints.module.aws_eks_teams[0].kubernetes_service_account.team["satellites"],
│   on .terraform/modules/eks_blueprints/modules/aws-eks-teams/main.tf line 152, in resource "kubernetes_service_account" "team":
│  152: resource "kubernetes_service_account" "team" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-kubernetes_v2.12.1_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 194 [running]:
github.com/hashicorp/terraform-provider-kubernetes/kubernetes.expandResourceQuotaSpec({0xc00082d3e0, 0x1, 0x0?})
	github.com/hashicorp/terraform-provider-kubernetes/kubernetes/structures.go:362 +0x2b7
github.com/hashicorp/terraform-provider-kubernetes/kubernetes.resourceKubernetesResourceQuotaCreate({0x2c858c8?, 0xc00047d980}, 0x2710800?, {0x28c25c0?, 0xc001c0c0e0})
	github.com/hashicorp/terraform-provider-kubernetes/kubernetes/resource_kubernetes_resource_quota.go:114 +0x1af
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000b0ba40, {0x2c85900, 0xc000898f60}, 0xd?, {0x28c25c0, 0xc001c0c0e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:342 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b0ba40, {0x2c85900, 0xc000898f60}, 0xc000d375f0, 0xc000071f00, {0x28c25c0, 0xc001c0c0e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:472 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000292288, {0x2c85900?, 0xc000898de0?}, 0xc002044d70)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000d14d50, 0xc000d14db0, {0xc001504c80, 0x2, 0x2}, 0xc000d14d80, 0xc00082c1e0, 0xc0014b7f20, 0xc000d14de0}, {0x2c85858, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.6.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000739cc0, {0x2c85900?, 0xc0012ffad0?}, 0xc0012fa5b0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x28bb660?, 0xc000739cc0}, {0x2c85900, 0xc0012ffad0}, 0xc00047cb40, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032f500, {0x2c89978, 0xc000180000}, 0xc000656000, 0xc001545c80, 0x3a79160, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00032f500, {0x2c89978, 0xc000180000}, 0xc000656000, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-kubernetes_v2.12.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0039] Terraform invocation failed in [...PATH...]
ERRO[0039] 1 error occurred:
	* exit status 1
```

I know that the problem looks to come from the plugin, but I also think that the problem could be that the `kubernetes_resource_quota` resource is being created with an empty spec, as you can see in the example:
```
# module.eks_blueprints.module.aws_eks_teams[0].kubernetes_resource_quota.this["satellites"] will be created
  + resource "kubernetes_resource_quota" "this" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "quotas"
          + namespace        = "namespace_1"
          + resource_version = (known after apply)
          + uid              = (known after apply)
        }

      + spec {
        }
    }
```

Should we add a count attribute taking into account the definition of the `quota` attribute in the application_teams map? I was thinking on create a new local map with only the teams that have quotas specified and use it in the for_each attribute:

```
# ---------------------------------------------------------------------------------------------------------------------
# Quotas
# ---------------------------------------------------------------------------------------------------------------------
resource "kubernetes_resource_quota" "this" {
  for_each = local.teams_quota_map

  metadata {
    name      = "quotas"
    namespace = kubernetes_namespace.team[each.key].metadata[0].name
  }

  spec {
    hard = try(each.value.quota, {})
  }
}
```

 If you agree I will create the PR.

**Comment by Zvikan** [comment]
Thank you for reporting this, can confirm this is reproducing on my end as-well, the following change does work and seem to be a better approach then setting default `{}` to the spec which seems to be the issue as mentioned.

```
resource "kubernetes_resource_quota" "this" {
  for_each = { for team_name, team_data in var.application_teams : team_name => team_data if lookup(team_data, "quota", "") != "" }

  metadata {
    name      = "quotas"
    namespace = kubernetes_namespace.team[each.key].metadata[0].name
  }

  spec {
    hard = try(each.value.quota, {})
  }
}
```

In short, change applies to not even bother creating the resource if quota is not mentioned.
Creating a PR shortly, please feel free to test this out.
